### ISSUE TITLE
Code organisation

### ISSUE THREAD

**Issue by raacampbell** [LidkeLab/matlab-instrument-control#124]
This comment is associated with a [manuscript review](https://github.com/openjournals/joss-reviews/issues/7275).

This software project has a large number of related classes and organising them better would help with feature discovery and long term maintainability.  Specifically:

* [x] Placing all MATLAB code into a single folder called `code`, `src`, or whatever is deemed suitable. This way it is clearer what folder(s) users should be adding to the MATLAB path. 
* [x] Refactor to organise classes in a [tree of namespace folders](https://uk.mathworks.com/help/matlab/matlab_oop/namespaces.html).

I realise the second point will involve a lot or refactoring of both this project and projects that depend upon it, however this is really is the gold standard way of structuring projects like this in MATLAB. It will pay for itself down the line and modern editors or IDEs make this sort of thing pretty painless. A structure along these sort of lines would make sense:

```
code/
code/+mic/
code/+mic/+camera
code/+mic/+camera/@abstract
code/+mic/+camera/@example
code/+mic/+camera/@DCAM4Camera
code/+mic/+linearstage
code/+mic/+linearstage/@abstract
...
```

Following this, you call at the command line as follows:
```
mDCAM = mic.camera.DCAM4Camera; 
```

This will help with feature discovery, since classes such as [MIC_ActiveReg3D](https://github.com/LidkeLab/matlab-instrument-control/blob/main/%40MIC_ActiveReg3D/MIC_ActiveReg3D.m), which is a much higher level entity, will not be lumped in with all the lower level stuff and abstract classes.

**Comment by sajjad88** [comment]
The hierarchical code/+mic/ is a great idea. Now our new MIC organization is as per the suggestions where we have used src/ as the Matlab source directory. We are providing an example startup.m file in the top level directory for this new code organization.

**Comment by raacampbell** [comment]
The "example" `startup.m` file is not ideal. If the user starts MATLAB in the same directory as the file then it generates errors due to non-existent folders. 

```
> In path (line 109)
In addpath>doPathAddition (line 126)
In addpath (line 90)
In startup (line 2) 
Warning: Name is nonexistent or not a directory: /home/rob/Downloads/matlab-instrument-control/\Users\sajja\Documents\MATLAB\matlab-instrument-control\src 
> In path (line 109)
In addpath>doPathAddition (line 126)
In addpath (line 90)
In startup (line 2) 
Warning: Name is nonexistent or not a directory: /home/rob/Downloads/matlab-instrument-control/C 
> In path (line 109)
In addpath>doPathAddition (line 126)

etc
```


It is trivial to add these directories to the path so you don't really need an example:
1. Add instructions stating the user should add the three folders to the path and remove the `startup.m`
2. Perhaps better yet, write a function that automatically adds the right folders to the path. The easiest way to do this is to (a) move mex64 into src then (b) you can generate the path to add with `genpath('src')`. [This is what is happening here](https://github.com/SWC-Advanced-Microscopy/BakingTray/blob/master/addBTtopath.m)

**Comment by sajjad88** [comment]
We added the function setupMIC.m in the top-level directory to set up the proper paths for the matlab-instrument-control repository.  In the README, we added the comment:

To set up the correct MATLAB path for MIC in startup.m (typically located in the Documents\MATLAB folder in the user's home directory), add the line

run(fullfile(userpath, 'matlab-instrument-control', 'setupMIC'))

(for MATLAB 2017a or more recent versions).
