### ISSUE TITLE
Provide a list of similar or related projects

### ISSUE THREAD

**Issue by raacampbell** [LidkeLab/matlab-instrument-control#126]
This comment is associated with a https://github.com/openjournals/joss-reviews/issues/7275.

It would be great to have a list of similar or related MATLAB projects in the README. [lsmacq](https://github.com/danionella/lsmaq) comes to mind, but there must be others.

**Comment by sajjad88** [comment]
In the top-level `Readme.md`, we have added the section “Related software”

**Comment by raacampbell** [comment]
What related MATLAB projects are there? [lsmacq](https://github.com/danionella/lsmaq) is one.

**Comment by sajjad88** [comment]
We have added LSMAQ in the paper and Readme.md files.
