### ISSUE TITLE
MIC_Attenuator: list example devices

### ISSUE THREAD

**Issue by raacampbell** [LidkeLab/matlab-instrument-control#136]
What devices is https://github.com/LidkeLab/matlab-instrument-control/blob/main/%40MIC_Attenuator/Readme.md designed for? EOMs? AOMs? LED drivers?

**Comment by sajjad88** [comment]
This class is designed for controlling Liquid Crystal Optical Beam Shutters / Variable Attenuators optical attenuators (example: Thorlabs LCC1620A, Liquid Crystal Optical Shutter, 420 - 700 nm) through a NI DAQ card, providing precise adjustments to the attenuation level. The same comment is also now part of `matlab-instrument-control/src/+mic/@Attenuator/Attenuator.m` and corresponding Readme.md file.
