### ISSUE TITLE
Are if statements correct in MC_Attenuator around Line 138? 

### ISSUE THREAD

**Issue by raacampbell** [LidkeLab/matlab-instrument-control#137]
https://github.com/LidkeLab/matlab-instrument-control/blob/679b5d694ace944a88d70bc71349bbb46d736581/%40MIC_Attenuator/MIC_Attenuator.m#L138

Why not use `>=` and `<=` rather than adding or subtracting a small number?

```
            if Transmission_in >obj.MaxTransmission+0.001
               error('The input transmission is too large, setting to %d\n',obj.MaxTransmission); 
            end
            if Transmission_in<obj.MinTransmission-0.001
               error('The input transmission is too small, setting to %d\n',obj.MinTransmission); 
            end
```

**Comment by sajjad88** [comment]
The use of +0.001 and -0.001 in this function was likely intended to provide a small tolerance for floating-point comparisons. This practice is common when dealing with floating-point arithmetic because exact equality can sometimes fail due to rounding errors.

**Comment by raacampbell** [comment]
This is not a test for an exact equality -- it is a test for if a number exceeds another number -- thus the floating point "fudge factor" is not relevant here.  I ran this point by another programmer and we both agree. In this instance it makes more sense to remove the fudge factor and do a straight comparison based on the raw calibration curve you obtained. The code is confusing otherwise. 

Additionally: are you sure you want to generate an error if the value is exceeded? Wouldn't this stop execution of the code? Does it not make more sense to `fprintf` to the screen or raise a warning and `return` early?

**Comment by sajjad88** [comment]
I have implemented your suggestions in attenuator class. Thank you.
