### ISSUE TITLE
PM100D class measures temperature correctly but laser power measurements just a very large value

### ISSUE THREAD

**Issue by raacampbell** [LidkeLab/matlab-instrument-control#138]
I always get "9.9100e+40" when measuring laser power. I tried different sensor heads.

**Comment by sajjad88** [comment]
Thank you for suggesting the changes in the PM100D class. We tested PM100D.m class on our power meter and it works for us. We have implemented your changes into our [src](https://github.com/LidkeLab/matlab-instrument-control/tree/code_reorg_clean/src)/[+mic](https://github.com/LidkeLab/matlab-instrument-control/tree/code_reorg_clean/src/%2Bmic)/[+powermeter](https://github.com/LidkeLab/matlab-instrument-control/tree/code_reorg_clean/src/%2Bmic/%2Bpowermeter)/@PM100D.m
