### ISSUE TITLE
Provide automated test output

### ISSUE THREAD

**Issue by bencardoen** [LidkeLab/matlab-instrument-control#141]
There are github workflows defined, but no public reported tests. 

Please provide integration of CI/CD (Travis/CirceCI are free for open source) to ensure your project's integrtiy is retained across commits.

**Comment by sajjad88** [comment]
Simulated classes produce testing. It’s not possible to test the instrument if not connected to the computer. However, despite our comments about hardware, we can test the simulated (and hence the) abstract classes with the MATLAB unittest framework, so we have added runtests to the source code repository, which we have set an action to run automatically on a push or pull request to the main branch.
