### ISSUE TITLE
Abstract Camera code review

### ISSUE THREAD

**Issue by bencardoen** [LidkeLab/matlab-instrument-control#143]
This comment is associated with a https://github.com/openjournals/joss-reviews/issues/7275.

- HDF5 does not seem supported? 

- Ranges for properties are only partially implemented, yet comments suggest these exist. Please complete these. https://github.com/LidkeLab/matlab-instrument-control/blob/7995050b9c37e0eb8c9ac8a0cbab165b3a9404c9/%40MIC_Camera_Abstract/MIC_Camera_Abstract.m#L51

- A lot of undocumented behavior is hardcoded in an abstract class, this should be documented, and configurable. The code of these methods is on the long side as well, consider refactoring into helper functions. https://github.com/LidkeLab/matlab-instrument-control/blob/main/%40MIC_Camera_Abstract/MIC_Camera_Abstract.m#L134

**Comment by sajjad88** [comment]
• For your comment about “HDF5 does not seem supported”, we decided to simplify the SaveType to only ‘mat’. However, we can save the data in HDF5 in software related to particular microscopes. For reference, please see ‘High-level implementation of MIC classes’ and ‘Projects using MIC’ in the top-level Readme, where we use higher level data collection implementations build on software in MIC.  We decided not to bundle these higher-level data collection routines with MIC, but separate them into their own repositories depending on microscope type (e.g., TIRF, sequential), and use these software to store results into HDF5.
• We removed the SaveType = ‘ics’, but retained the variable SaveType for future expansion. 
• Further documentation has been added to camera abstract class.
