### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by bencardoen** [LidkeLab/matlab-instrument-control#145]
This comment is associated with a https://github.com/openjournals/joss-reviews/issues/7275.

At this point the documentation is extracted from Matlab comments using a custom script. 
However, the generated markdown documentation is not 1-1 with the actual code. 

There are github actions defined, they do not call the documentation generation script, however. 

Please:
- Avoid reinventing the wheel, there are well documented alternatives to generating documentation from matlab annotated source code https://stackoverflow.com/questions/26242145/ 
- Automate this so documentation is _alway_ 1-1 with code

**Comment by sajjad88** [comment]
We would really like to create .md files for the MIC documentation as they show up nicely when we web browse GitHub (as we did with our previously published JOSS code, SMITE).  MATLAB's "publish" outputs a variety of formats, but not Markdown, and the other tools referenced in the stackoverflow link produce HTML but not Markdown.  GitHub does not natively interpret the file
README.html, so each solution requires some non-standard tweaking.  Given that, we prefer to use our script to generate README.md files directly. We have added a GitHub action to automatically generate the documentation README.md files every time a push or pull request to the main branch is made.
